function buildLibraryArray(){
	var libarray = {
	"AFR":"Afro-American Studies",
	"AJP":"Andover Newton Theol",
	"ANT":"Andover-Harv. Theol",
	"ARG":"Baker Business",
	"ARN":"Baker Business",
	"ART":"Biblioteca Berenson",
	"BAK":"Biological Labs",
	"BER":"Birkhoff Math",
	"BIO":"Blue Hill",
	"BIR":"Boston College",
	"BKO":"Botany Ames Orchid",
	"BLH":"Botany Arboretum",
	"BRM":"Botany Arnold (Cambr.)",
	"BUT":"Botany Econ. Botany",
	"CAB":"Botany Farlow Library",
	"CAR":"Botany Gray Herbarium",
	"CEA":"Botany Gray/Arnold",
	"CEL":"BU School of Theol",
	"CFI":"Busch-Reisinger Mus",
	"CHE":"Cabot Science",
	"CHI":"Carpenter Center",
	"CRL":"Charles Warren Ctr Lib",
	"DAN":"Chemistry",
	"DCJ":"Child Memorial",
	"DDO":"Countway Medicine",
	"DES":"CRL (Ctr for Research Libs)",
	"DEV":"Ctr Eur Studies",
	"DIV":"Ctr Hellen Studies",
	"DOC":"Ctr Intl Affairs",
	"ECB":"Derek Bok Center",
	"EDS":"Development Office",
	"ENV":"Doc Ctr Japan",
	"EUR":"Documents (Lamont)",
	"FAL":"Dumbarton Oaks",
	"FAR":"East Asian Res Ctr",
	"FIG":"EDS/Weston",
	"FOG":"EDS/Weston",
	"FOR":"Environmental Information Ctr",
	"FUN":"Fine Arts",
	"GCT":"Fogg Museum",
	"GDC":"Fung Library",
	"GEO":"Gibb Islamic",
	"GIB":"Gordon-Conwell",
	"GRA":"Grossman",
	"GRO":"Gutman Education",
	"GUT":"Harvard Art Museums",
	"HCR":"Harvard Data Center",
	"HEL":"Harvard Film Archive",
	"HFA":"Harvard Forest",
	"HIL":"Harvard Planning & Real Estate",
	"HIS":"Harvard University Archives",
	"HOU":"Harvard University Library",
	"HPO":"Harvard-Yenching",
	"HSI":"Hilles",
	"HSL":"History Dept",
	"HUA":"History of Science",
	"HUL":"Holy Cross Orthodox",
	"HYL":"Houghton",
	"KIR":"Kennedy Sch of Gov",
	"KSG":"Kirkland House",
	"LAM":"Kummel Geological Sci",
	"LAW":"Lamont",
	"LIN":"Law School",
	"LIT":"Linguistics",
	"MAP":"Littauer",
	"MCK":"Loeb Design",
	"MCZ":"Loeb Music",
	"MED":"Map Coll (Pusey)",
	"MIC":"Master Microforms",
	"MMF":"McKay Applied Sci",
	"MUR":"Medieval Studies Lib",
	"MUS":"Microforms (Lamont)",
	"NEL":"Murray Research Ctr",
	"NET":"Museum Comp Zoology",
	"NMM":"National master micro",
	"OPH":"Near Eastern Lib",
	"ORC":"Networked Resource",
	"PAL":"Networked Resource",
	"PEA":"Ophthalmology",
	"PHI":"Peabody Museum",
	"PHY":"Physics Research",
	"POE":"Poetry Room (Lamont)",
	"PRI":"Primate Center Lib",
	"PSY":"Psychology Research",
	"PUS":"Pusey",
	"QUA":"Quad Library",
	"RCA":"Radcliffe Archives",
	"RRC":"Robbins Philosophy",
	"RUB":"Robinson Celtic",
	"SAN":"Rubel (Fine Arts)",
	"SBC":"Russian Res Ctr",
	"SCC":"Sanskrit Library",
	"SCH":"Schering Health Care",
	"SFL":"Schlesinger",
	"SIA":"Sci & Intl Affairs",
	"SMY":"Sci Instruments",
	"SOC":"Smyth Classical",
	"STA":"Social Rel-Sociol",
	"STJ":"Solidarity Bibl Center",
	"TBC":"St John's Seminary",
	"THE":"Statistics",
	"TOZ":"Straus Conservation",
	"URI":"Theatre Collection",
	"WAM":"Tozzer",
	"WAR":"Ukrainian Res Inst",
	"WEI":"Warren Anatomical",
	"WES":"Weissman Preservation Ctr",
	"WID":"Widener",
	"WOL":"Wolbach Library"
	}
	return libarray;
}